### ISSUE TITLE
PLEASE UPDATE

### ISSUE THREAD

**Issue by Adhaaz** [lamhoang1256/youme#1]
Hi sir 👋 I love your project, but it seems something is missing.. Can you add playerKey, keyboardShortcut, Video Download Button and poster in video player section.. hopefully my request will be added to the source code as soon as possible.. thank youu sir

**Comment by Adhaaz** [comment]
Please Respond 😌

**Comment by lamhoang1256** [comment]
> 
Thank you for liking my project, about the video player I have a reference here https://react-tuby.vercel.app/

**Comment by lamhoang1256** [comment]
> Please Respond relieved

Thank you for liking my project, about the video player I have a reference here https://react-tuby.vercel.app/

**Comment by lamhoang1256** [comment]
> Please Respond relieved
I will update soon to make the project more complete, thank you for your contribution

**Comment by lamhoang1256** [comment]
> Please Respond relieved
I will update soon to make the project more complete, thank you for your contribution 🥰

**Comment by lamhoang1256** [comment]
> Please Respond 😌

Once again, thank you for your feedback, if you have any ideas, I will try to improve it as soon as possible.

**Comment by Adhaaz** [comment]
Okay sir, thx 🙏
